default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
to-the-moon: styles/to-the-moon.scss
infinity-bridge: styles/infinity-bridge.scss
stardew-valley: styles/stardew-valley.scss
cafe: styles/café.scss
flora: styles/flora.scss
test: styles/sheep.scss