default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
to-the-moon: styles/to-the-moon.scss
stardew-valley: styles/stardew-valley.scss
cafe: styles/café.scss
flora: styles/flora.scss
black-cat: styles/black-cat.scss
test0: styles/sheep.scss
test1: styles/strawberry.scss
